name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build twine jupyterlab
    - name: Build the federated extension in a separated build environment
      run: |
        python -m build
    - name: Publish the Python package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    - name: Build the source extension
      run: |
        jlpm
        jlpm build
    - name: Publish the NPM package
      run: |
        echo $PRE_RELEASE
        if [[ $PRE_RELEASE == "true" ]]; then export TAG="next"; else export TAG="latest"; fi
        npm publish --tag ${TAG} --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        PRE_RELEASE: ${{ github.event.release.prerelease }}
